name: on-robot

services:
  on-robot:
    environment:
      - on-robot
      - DISPLAY                              # Req'd for RViz
    env_file:
    - .env
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_ACCESS_TOKEN=${GIT_ACCESS_TOKEN}
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.001'
    #      memory: 500M
    #    reservations:
    #      cpus: '0.0001'
    #      memory: 100M
    network_mode: host
    ipc: host
    privileged: true                         # Req'd for RViz and USB hardware
    volumes:                                 # Req'd for RViz
      - $XAUTHORITY:/root/.Xauthority        # Req'd for RViz
    # command: sleep infinity
    command: roslaunch kmr_iiwa_ifl_bringup real_kmr_bringup.launch
    # command: roscore
